services:
  backend:
    build:
      context: ./backend
    container_name: jlabs-backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: jlabs-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    restart: unless-stopped
