FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY .env .env

RUN npm install -g prisma

RUN npx prisma generate
RUN npx prisma migrate deploy || true
RUN npm run seed

EXPOSE 3000

CMD ["node", "app.js"]
